server:
  port: 8080

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8181/realms/spring-microservices-realm"

  cloud:
    gateway:
      mvc:
        routes:
          - id: order_service_swagger
            uri: http://localhost:8081
            predicates:
              - Path=/aggregate/order-service/v3/api-docs
            filters:
              - SetPath=/api-docs
          - id: product_service_swagger
            uri: http://localhost:8082
            predicates:
              - Path=/aggregate/product-service/v3/api-docs
            filters:
              - SetPath=/api-docs
          - id: inventory_service_swagger
            uri: http://localhost:8083
            predicates:
              - Path=/aggregate/inventory-service/v3/api-docs
            filters:
              - SetPath=/api-docs

          - id: order_service
            uri: http://localhost:8081
            predicates:
              - Path=/api/order, /api/order/**
          - id: product_service
            uri: http://localhost:8082
            predicates:
              - Path=/api/product, /api/product/**
          - id: inventory_service
            uri: http://localhost:8083
            predicates:
              - Path=/api/inventory, /api/inventory/**


springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Product Service
        url: /aggregate/product-service/v3/api-docs
      - name: Order Service
        url: /aggregate/order-service/v3/api-docs
      - name: Inventory Service
        url: /aggregate/inventory-service/v3/api-docs
  api-docs:
    enabled: true
    path: /api-docs
