services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - /c/docker/data/spboot-ms/mongo-product:/data/db




#      - /d/me/learn/springboot/microservices/YT-programming-techie/practise/spring-boot-3-microservices-course/spring-boot-3-microservices/mongodb-volume:/data/db
#        C:\docker\data\spboot-ms\mongodb