
server:
  port: 8083

spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: mongodb://root:password@127.0.0.1:27017/?authSource=admin
      database: product-service
      auto-index-creation: true
      type-key: ""

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus


#spring.application.name=product-service
#
#spring.data.mongodb.uri=mongodb://root:password@127.0.0.1:27017/?authSource=admin
#spring.data.mongodb.database=product-service
#spring.data.mongodb.auto-index-creation=true
#spring.data.mongodb.type-key=
#
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.api-docs.path=/api-docs
#
#management.endpoints.web.exposure.include=health,info,metrics,prometheus