services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-inventory-service
    ports:
      - "3337:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - /c/docker/data/spboot-ms/mysql-inventory:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
